skip_on_cran()

test_that("get_* fxn deprecations", {
  # new fxn - old fxn
  expect_identical(get_bold, get_boldid)
  expect_identical(get_bold_, get_boldid_)
  expect_identical(get_eol, get_eolid)
  expect_identical(get_eol_, get_eolid_)
  expect_identical(get_gbif, get_gbifid)
  expect_identical(get_gbif_, get_gbifid_)
  expect_identical(get_itis, get_tsn)
  expect_identical(get_itis_, get_tsn_)
  expect_identical(get_natserv, get_natservid)
  expect_identical(get_natserv_, get_natservid_)
  expect_identical(get_nbn, get_nbnid)
  expect_identical(get_nbn_, get_nbnid_)
  expect_identical(get_ncbi, get_uid)
  expect_identical(get_ncbi_, get_uid_)
  expect_identical(get_tol, get_tolid)
  expect_identical(get_tol_, get_tolid_)
  expect_identical(get_tps, get_tpsid)
  expect_identical(get_tps_, get_tpsid_)
  expect_identical(get_worms, get_wormsid)
  expect_identical(get_worms_, get_wormsid_)
})

test_that("get_* fxn throws warning when old function used", {
  vcr::use_cassette("deprecated_get_fxns", {
    expect_warning(get_uid("howdy", messages=FALSE), "deprecated")
    expect_warning(get_uid("howdy", messages=FALSE), NA)
    expect_warning(get_tsn("howdy", messages=FALSE), "deprecated")
    expect_warning(get_tsn("howdy", messages=FALSE), NA)
    expect_warning(get_boldid("howdy", messages=FALSE), "deprecated")
    expect_warning(get_boldid("howdy", messages=FALSE), NA)
    expect_warning(get_gbifid("howdy", messages=FALSE), "deprecated")
    expect_warning(get_gbifid("howdy", messages=FALSE), NA)
    expect_warning(get_eolid("howdy", messages=FALSE), "deprecated")
    expect_warning(get_eolid("howdy", messages=FALSE), NA)
    expect_warning(get_natservid("howdy", messages=FALSE), "deprecated")
    expect_warning(get_natservid("howdy", messages=FALSE), NA)
    expect_warning(get_nbnid("howdy", messages=FALSE), "deprecated")
    expect_warning(get_nbnid("howdy", messages=FALSE), NA)
    expect_warning(get_tolid("helianthus", messages=FALSE), "deprecated")
    expect_warning(get_tolid("helianthus", messages=FALSE), NA)
    expect_warning(get_tpsid("howdy", messages=FALSE), "deprecated")
    expect_warning(get_tpsid("howdy", messages=FALSE), NA)
    expect_warning(get_wormsid("howdy", messages=FALSE), "deprecated")
    expect_warning(get_wormsid("howdy", messages=FALSE), NA)
  })
})
