\documentclass[letterpaper,superscriptaddress,showkeys,longbibliography,10pt]{revtex4-1}
\usepackage[utf8]{inputenc}
\usepackage{color,dcolumn,graphicx,hyperref}
\usepackage{natbib}
\usepackage{footnote}
\hypersetup
{
colorlinks = true, linkcolor = blue, citecolor = blue, urlcolor = blue,
}

\begin{document}

<<setup, include=FALSE, cache=FALSE>>=
## set global chunk options
opts_chunk$set(fig.path='figure/', fig.align='center', fig.show='hold', par=TRUE, warning=FALSE, message=FALSE, error=FALSE, comment=NA)
@

\section{Appendix A. A complete reproducible workflow, from a species list to a phylogeny, and distribution map.}

If you aren't familiar with a complete workflow in R, it may be difficult to visualize the processs. In R, everything is programmatic, so the whole workflow can be in one place, and be repeated whenever necessary. The following is a workflow for taxize, going from a species list to a phylogeny. 


First, install taxize

<<install, eval=FALSE>>=
install.packages("taxize")
@

Then load it into R

<<load, eval=TRUE>>=
library(taxize)
@

Most of us will start out with a species list, something like the one below. Note that each of the names is spelled incorrectly.

<<thespecieslist, eval=TRUE>>=
splist <- c("Helanthus annuus", "Pinos contorta", "Collomia grandiflorra", "Abies magnificaa", 
  	"Rosa california", "Datura wrighti", "Mimulus bicolour", "Nicotiana glauca",
		"Maddia sativa", "Bartlettia scapposa")
@

There are many ways to resolve taxonomic names in taxize. Of course, the ideal name resolver will do the work behind the scenes for you so that you don't have to do things like fuzzy matching. There are a few services in taxize like this we can choose from: the Global Names Resolver service from EOL (see function \emph{gnr\_resolve}) and the Taxonomic Name Resolution Service from iPlant (see function \emph{tnrs}). In this case let's use the function \emph{tnrs}. 

<<resolvenames, eval=TRUE>>=
# The tnrs function accepts a vector of 1 or more
splist_tnrs <- tnrs(query=splist, getpost="POST", source_ = "iPlant_TNRS")

# Remove some fields
(splist_tnrs <- splist_tnrs[,!names(splist_tnrs) %in% c("matchedName","annotations","uri")])

# Note the scores. They suggest that there were no perfect matches, but they were all very close, ranging from 0.77 to 0.99 (1 is the highest). 
# Let's assume the names in the "acceptedName" column are correct (and they should be).

# So here's our updated species list
(splist <- as.character(splist_tnrs$acceptedName))
@

Another thing we may want to do is collect common names for our taxa. 

<<commonnames, eval=TRUE>>=
tsns <- get_tsn(searchterm=splist, searchtype="sciname", verbose=FALSE)
comnames <- lapply(tsns, getcommonnamesfromtsn)

# Unfortunately, common names are not standardized like species names, so there are multiple common names for each taxon
sapply(comnames, length)

# So let's just take the first common name for each species
comnames_vec <- do.call(c, lapply(comnames, function(x) as.character(x[1,"comname"])))

# And we can make a data.frame of our scientific and common names
(allnames <- data.frame(spname = splist, comname = comnames_vec))
@

Another common task is getting the taxonomic tree upstream from your study taxa. We often know what family or order our taxa are in, but it we often don't know the tribes, subclasses, and superfafamilies. taxize provides many avenues to getting classifications. Two of them are accesible via a single function (\emph{classification}): the Integrated Taxonomic Information System and uBio; and via the Catalogue of Life (see function \emph{col\_classification})

<<classification, eval=TRUE>>=
# As we already have Taxonomic Serial Numbers from ITIS, let's just get classifications from ITIS. Note that we could use uBio instead.
class_list <- classification(tsns)
sapply(class_list, nrow)

# And we can attach these names to our allnames data.frame
library(plyr)
gethiernames <- function(x){
  temp <- x[,c("rankName","taxonName")]
  values <- data.frame(t(temp[,2]))
  names(values) <- temp[,1]
  return( values )
}
class_df <- ldply(class_list, gethiernames)
allnames_df <- merge(allnames, class_df, by.x="spname", by.y="Species")

# Now that we have allnames_df, we can start to see some relationships among species simply by their shared taxonomic names
allnames_df[1:2,]

# Ah, so Abies and Bartlettia are in different infradivisions, but share taxonomic names above that point.
@

However, taxonomy can only get you so far. Shared ancestry can be reconstructed from molecular data, and phylogenies created. Phylomatic is a web service with an API that we can use to get a phylogeny. 

\begin{figure}[!ht] 
\centering 
<<phylogeny, eval=TRUE, dev='png', out.width='.8\\linewidth', out.height='4in'>>=
library(doMC)
registerDoMC(cores=4)  # I have a mac, so using doMC package, use whatever you like
phylogeny <- phylomatic_tree(taxa=as.character(allnames$spname), taxnames=TRUE, get = 'POST', informat='newick', method = "phylomatic",
    storedtree = "R20120829", taxaformat = "slashpath", outformat = "newick", clean = "true", parallel=TRUE)
phylogeny$tip.label <- capwords(phylogeny$tip.label, onlyfirst=TRUE)
plot(phylogeny)
@
\caption{a phylogeny...} 
\end{figure} 

Using the species list, with the corrected names, we can now search for occurrence data. The Global Biodiversity Information Facility (GBIF) has the largest collection of records data, and has a  API that we can interact with programmatically from R. First, we need to install rgbif.

<<installgbif, eval=FALSE>>=
# Install rgbif
install.packages("devtools")
library(devtools)
install_github("rgbif", "ropensci")
@

Now we can search for occurrences for our species list and make a map.

\begin{figure}[!ht] 
\centering 
<<map, eval=TRUE, dev='png', out.height='4in'>>=
library(doMC); library(rgbif)

occurr_list <- occurrencelist_many(as.character(allnames$spname), coordinatestatus = TRUE, maxresults = 100, removeZeros=TRUE, fixnames="changealltorig")

# Make a map
p <- rgbif::map(occurr_list)
p + guides(col = guide_legend(nrow = 2, byrow = TRUE)) + theme(legend.position="bottom")
@
\caption{a map...} 
\end{figure}

\bibliography{apprefs}
\end{document}