\documentclass{article}
%%\VignetteIndexEntry{taxize-intro}
%%\VignetteDepends{taxize}

\usepackage[utf8]{inputenc}

\begin{document}
\title{An Introduction to the taxize package}
\author{The taxize authors}

\maketitle

\tableofcontents

TODO: Introduction to package, explanation of function names,...

\section{Phylomatic}
\subsection{Fetch a phylogenetic tree from Phylomatic}
<<>>=
require(taxize)
mytree <- "asteraceae/bidens/bidens_cernua
asteraceae/madia/madia_exigua
asteraceae/helianthus/helianthus_annuus"
@

\subsubsection{Return a tree in the phylo object format}
<<>>=
phylomatic_tree(mytree, 'TRUE', 'GET', 'xml', 'TRUE') 
@

\subsubsection{Return a tree in the phylo object format, using POST method}
<<>>=
phylomatic_tree(mytree, 'TRUE', 'POST', 'xml', 'TRUE')
@

\subsubsection{Return tree in newick format}
<<>>=
phylomatic_tree(mytree, 'TRUE', 'GET', 'new', 'FALSE')
@


\subsection{Get a tree in newick format, read using ape::read.tree, and plot}
<<phylog1>>=
tree <- phylomatic_tree(mytree, 'TRUE', 'POST', 'new', 'FALSE')
require(ape)
treephylo <- read.tree(text = tree)
plot(treephylo)
@



\section{Integrated Taxonomic Informaiton Service (ITIS)}
\subsection{Search by term and search type}
Note: TSN stands for Taxonomic Serial Number
<<>>=
doc <- itis_get_xml("dolphin", "comname", "name")
doc <- itis_get_xml("grizzly bear", "comnameend", "name")
doc <- itis_get_xml("ursidae", "itistermssciname", "name")
@

\subsection{Take advantage of default arguments, spaces accepted, and display data.frame output}
<<>>=
doc <- itis_get_xml("Plethodon")
head(itis_parse(doc))
@

\subsection{Show higher taxonomy for a given TSN}
<<>>=
classification(685566, ID = "tsn")
@

\subsection{Get a TSN from a species name}
<<>>=
tsn <- get_tsn(searchterm = "Quercus_douglasii", searchtype = "sciname")
# use classification with get_tsn together:
classification(tsn)
@



\section{NCBI Taxonomy Browser}
\subsection{Get Unique Identifier}
<<>>=
uids <- get_uid(c("Chironomus riparius", "Chaetopteryx"))
@

\subsection{Retrieve classification for give UID}
<<>>=
cl <- classification(uids)
cl
@



\section{Using ITIS and Phylomatic together}
\subsection{Use ITIS and itis\_get\_phymat\_format to format a string for each species to be submitted to Phylomatic}
<<phylog2>>=
require(plyr)
dat <- laply(list("36616", "19322", "183327"), itis_get_phymat_format, format='rsubmit')
dat
dat_mine <- paste(dat, collapse="%0D%0A") # collapse and replace \n's
dat_mine
tree <- phylomatic_tree(dat_mine, 'FALSE', 'GET', 'new', 'TRUE')
tree
plot(tree)
@

\subsection{A somewhat realistic workflow}
\subsubsection{User's species list}
<<>>=
splist <- c("annona cherimola", 'annona muricata', 
  					"shorea robusta", "pandanus patina", "durio zibethinus")
@

\subsubsection{Get TSN code for each species}
<<>>=
tsns <- get_tsn(splist, "sciname")
tsns
@

\subsubsection{Get Phylomatic formatted strings for each species}
<<>>=
dat <- laply(tsns, itis_get_phymat_format, format = 'rsubmit')
dat
@

\subsubsection{Send strings to Phylomatic and return newick tree}
<<>>=
tree <- phylomatic_tree(dat, 'TRUE', 'GET', 'new', 'TRUE')
tree
@

\subsubsection{Plot tree, etc. }
<<phylog3>>=
plot(tree)
@



\section{Taxonomic Name Resolution Service}
\subsection{Name matching using the TNRS}
<<>>=
iplant_tnrsmatch('best', taxnames = c('helianthus annuus', 'acacia', 'saltea'), output = 'names') # just best names
@



\section{Global Names Resolver (GNR)}
\subsection{Get just id's and names of sources in a data.frame}
<<>>=
tail(gnr_datasources(todf = TRUE))
@

\subsection{Give me the id for EOL (Encyclopedia of Life)}
<<>>=
out <- gnr_datasources(todf = TRUE)
out[out$title == "EOL", "id"]
@

\subsection{Fuzzy search for sources with the word "zoo"}
<<>>=
out <- gnr_datasources(todf = TRUE)
outdf <- out[agrep("zoo", out$title, ignore.case = TRUE), ]
outdf[1:2,]
@

\subsection{Resolve some names}
\subsubsection{Search for \emph{Helianthus annuus} and \emph{Homo sapiens}, return a data.frame}
<<>>=
gnr_resolve(names = c("Helianthus annuus", "Homo sapiens"), returndf = TRUE)[1:2,]
@

\subsubsection{Search for the same species, with only using data source 12 (i.e., EOL)}
<<>>=
gnr_resolve(names = c("Helianthus annuus", "Homo sapiens"), data_source_ids="12", returndf = TRUE)
@



\section{Tropicos}
<<>>=
# need key
#head(tp_getacceptednames(id = 25503923))
#head(tp_getsynonyms(id = 25509881))
@



\section{uBio}
\subsection{Search uBio using the namebank\_search API method}
<<>>=
# need key
# ubio_namebank(searchName = 'elephant', sci = 1, vern = 0)
# head( ubio_namebank(searchName = 'Helianthus annuus', sci = 1, vern = 0)[,-c(2,3)] )
# out <- lapply(list('Helianthus debilis','Astragalus aduncus'), function(x) ubio_namebank(searchName = x, sci = 1, vern = 0))
# head( out[[2]][,-c(2,3)] ) # just Astragalus aduncus output
@



\section{IUCN Red List}
\subsection{Query the Red List API}
<<>>=
ia <- iucn_summary(c("Panthera uncia", "Lynx lynx"))
@

\subsection{Extract status}
<<>>=
laply(ia, function(x) x$status)
@

\subsection{Extract Distribution}
<<>>=
ia[['Panthera uncia']]$distr
@


\end{document}