on: push

name: revdep

jobs:
  revdep:
    runs-on: ${{ matrix.config.os }}
    if: startsWith(github.event.head_commit.message, 'REVDEPCHECK')
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})
    strategy:
      fail-fast: false
      matrix:
        config:
        - { os: macOS-latest, r: 'latest'}

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      CRAN: ${{ matrix.config.cran }}
      VCR_VERBOSE_ERRORS: true
      ENTREZ_KEY: ${{ secrets.ENTREZ_KEY }}
      IUCN_REDLIST_KEY: ${{ secrets.IUCN_REDLIST_KEY }}
      TROPICOS_KEY: ${{ secrets.ENTREZ_KEY }}

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1
        with:
          r-version: ${{ matrix.config.r }}

      - uses: r-lib/actions/setup-pandoc@v1

      - name: Cache R packages
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-${{ matrix.config.r }}-${{ hashFiles('DESCRIPTION') }}
      
      - name: Install dependencies
        run: Rscript -e "install.packages('remotes')" -e "remotes::install_deps(dependencies = TRUE)" -e "remotes::install_github('r-lib/revdepcheck')"

      - name: Revdepcheck
        run: Rscript -e "revdepcheck::revdep_reset()" -e "revdepcheck::revdep_check(num_workers=4)"

      - name: Upload revdepcheck results
        uses: actions/upload-artifact@v2
        with:
          name: ${{ runner.os }}-r${{ matrix.config.r }}-results
          path: revdep/*.md
